//! The objects in the game.

use crate::{Cooldown, Player};

/// An object.
#[derive(Clone, Debug)]
pub struct Object {
    /// The kind of the object.
    ///
    /// Contains kind-specific object information.
    pub kind: ObjectKind,

    /// The health of the object.
    pub health: u32,

    /// The maximum health of the object.
    pub max_health: u32,
}

/// The kind of an object.
///
/// Contains kind-specific object information.
#[derive(Clone, Debug)]
pub enum ObjectKind {
    /// A key object.
    Key {
        /// The amount of keys generated by the key object.
        generation: u32,
        /// The cooldown for key generation.
        cooldown: Cooldown,
    },
    /// A fire object.
    Fire {
        /// The amount of damage dealt by the fire object.
        damage: u32,
        /// The cooldown for attack.
        cooldown: Cooldown,
    },
}

/// An object owned by a player.
#[derive(Clone, Debug)]
pub struct OwnedObject {
    /// The object.
    pub object: Object,

    /// The owner of the object.
    pub owner: Player,
}
